spring:
    datasource:
        url: jdbc:mysql://presz.pl:3306/janpresz_exp2?useSSL=false
        username: janpresz_exp2
        password: janpresz_exp2
    jpa:
      generate-ddl: true
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
          ddl-auto: update
    data:
      rest:
        basePath: /api